SELECT SYSDATE FROM DUAL;

SELECT * FROM DBA_PROFILES;

-- 비밀번호 만료기간 UNLIMITED로 변경
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- 계정 비밀번호 변경
ALTER USER system IDENTIFIED BY "manager11" REPLACE "oracle";